Feature: describe videos

  As a volunteer
  So that I can provide audio descriptions for my friends
  First of all I want to find videos via a valid YouTube URL
  Then I want to add AD to them

Background: existing user

    Given the following users exist:
    | id | username    | auth0_id | options                |
    | 1  | vishnu.nair | asdffdsa | {"default_lang": "en"} |
    | 2  | xw2765      | fdsaasdf | {"default_lang": "en"} |
    | 3  | lyp2106     | jkl;;lkj | {"default_lang": "en"} |
 
Scenario: enter a valid URL to describe

    When I am on the home page

    And I fill in "yt_url" with "https://www.youtube.com/watch?v=40z9n1SgozU"

    And I press "Describe"

    Then I should be on the show page for "40z9n1SgozU"

    And I should see "Transitions"

Scenario: enter a valid URL generated by Share to describe

    When I am on the home page

    And I fill in "yt_url" with "youtu.be/40z9n1SgozU?t=57"

    And I press "Describe"

    Then I should be on the show page for "40z9n1SgozU"

    And I should see "Transitions"

Scenario: enter an invalid URL to describe

    When I am on the home page

    And I fill in "yt_url" with "https://www.youtube.com/watch?v=40z9n"

    And I press "Describe"

    Then I should see "Sorry, we couldn't find a video with that YouTube link."

Scenario: add one generated description for the video I found
    
    When I am on the home page

    And I fill in "yt_url" with "https://www.youtube.com/watch?v=40z9n1SgozU"

    And I press "Describe"

    Then I should be on the show page for "40z9n1SgozU"

    And I should see "This video does not yet have audio descriptions."

    And I press "Describe this video"

    And I should see "Describe video: Transitions"

    And I press "Add one new generated description at current time!"

    Then I should see "time (sec):"

    And I should see "Voice speed:"
    
    And I fill in "description" with "people walking around"

    And I fill in "time" with "3.1"

    And I fill in "voice_speed" with "1.5"

    And I select "extended" from "pause_at_start_time"

    And I select "Voice US C" from "voice_id"

    Then I press "Add"

    Then should contain "3.1"

    Then I should see "extended"