Feature: describe videos

  As a user
  I need to check if a YouTube video is available
  So that I could listen or provide audio descriptions for it

Scenario: enter a valid URL to describe

    When I am on the home page

    And I fill in "yt_url" with "https://www.youtube.com/watch?v=40z9n1SgozU"

    And I press "Describe"

    Then I should be on the show page for "40z9n1SgozU"

    And I should see "Transitions"

Scenario: enter a valid URL generated by Share to describe

    When I am on the home page

    And I fill in "yt_url" with "youtu.be/40z9n1SgozU?t=57"

    And I press "Describe"

    Then I should be on the show page for "40z9n1SgozU"

    And I should see "Transitions"

Scenario: enter an invalid URL to describe

    When I am on the home page

    And I fill in "yt_url" with "https://www.youtube.com/watch?v=40z9n"

    And I press "Describe"

    Then I should see "Sorry, we couldn't find a video with that YouTube link."